import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import WorkoutContextProvider from "../../../common/context/workoutContext";
import Header from "../../../components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WorkoutContextProvider>
          <div className="wrapper">
            <Header />
            <main className="page">{children}</main>
          </div>
        </WorkoutContextProvider>
      </body>
    </html>
  );
}
